services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,sqs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "./terraform/lambda:/lambda"
      - "/var/run/docker.sock:/var/run/docker.sock"
